# Generated by Django 2.2.5 on 2020-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyllaPro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Log',
            fields=[
                ('Login_Seq', models.IntegerField(primary_key=True, serialize=False)),
                ('Login_ID', models.CharField(max_length=500)),
                ('IP', models.CharField(max_length=50)),
                ('PC_Name', models.CharField(max_length=50)),
                ('Accdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('professor_name', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=100)),
                ('grades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject_basket',
            fields=[
                ('subject_Seq', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_ID', models.CharField(max_length=50)),
                ('Basket_Code', models.IntegerField()),
                ('processing_result', models.BooleanField(default=False)),
            ],
        ),
    ]
